"use client";

import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function AISummaryPanel() {
  const [summary, setSummary] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [provider, setProvider] = useState("AI");
  const [lastUpdated, setLastUpdated] = useState<string | null>(null);

  async function generateSummary() {
    setIsLoading(true);
    setSummary("");

    try {
      const response = await fetch("/api/ai/summarize", { method: "POST" });
      setProvider(response.headers.get("x-ai-provider") ?? "AI");

      const reader = response.body?.getReader();
      if (!reader) throw new Error("Missing stream");

      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        setSummary((previous) => previous + decoder.decode(value));
      }

      setLastUpdated(new Date().toLocaleTimeString("id-ID"));
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Card className="fade-up overflow-hidden border-primary/15 bg-gradient-to-br from-primary/8 via-card to-accent/35">
      <CardHeader className="flex-col gap-4">
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-primary">AI dashboard summary</p>
          <CardTitle className="mt-3 flex items-center gap-2 text-xl md:text-2xl">
            <Sparkles className="h-5 w-5 text-primary" />
            Insight otomatis untuk manajemen
          </CardTitle>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">Analisis otomatis berdasarkan statistik dashboard, print log, dan anomali aktivitas yang terlihat di halaman ini.</p>
        </div>
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-[24px] border border-border bg-background/70 p-4">
          <div>
            <p className="text-sm font-semibold">Ringkasan siap dibuat kapan saja</p>
            <p className="mt-1 text-sm text-muted-foreground">{lastUpdated ? `Diperbarui ${lastUpdated}` : "Belum ada ringkasan terbaru"}</p>
          </div>
          <Button onClick={generateSummary} disabled={isLoading} className="rounded-full">
            {isLoading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <RefreshCw className="h-4 w-4" />
                Generate
              </>
            )}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {!summary && !isLoading && (
          <div className="rounded-[24px] border border-dashed border-border bg-background/40 px-6 py-12 text-center text-sm text-muted-foreground">
            Klik Generate untuk mendapatkan insight eksekutif dari data dashboard.
          </div>
        )}
        {isLoading && !summary && (
          <div className="flex items-center justify-center gap-3 rounded-[24px] bg-background/40 px-6 py-12 text-sm text-muted-foreground">
            <Loader2 className="h-5 w-5 animate-spin" />
            AI sedang menganalisis data dashboard...
          </div>
        )}
        {summary && (
          <>
            <div className="whitespace-pre-wrap rounded-[24px] border border-border bg-background/70 p-6 text-sm leading-7 text-foreground">
              {summary}
            </div>
            <p className="mt-3 text-right text-xs text-muted-foreground">Generated by {provider}</p>
          </>
        )}
      </CardContent>
    </Card>
  );
}
