import type {
  DashboardStats,
  PrintFeedItem,
  PrintHistoryItem,
  ReportListItem,
} from "@/types";

export const demoReports: ReportListItem[] = [
  {
    id: "rpt-sales-q1",
    title: "Rekap Penjualan Q1 2026",
    description: "Laporan penjualan seluruh region untuk triwulan pertama.",
    category: "Sales",
    fileType: "PDF",
    status: "PUBLISHED",
    tags: ["sales", "q1", "2026"],
    printCount: 47,
    createdBy: { id: "usr-budi", name: "Budi Santoso", department: "Sales" },
    createdAt: "2026-03-01T08:30:00.000Z",
    updatedAt: "2026-03-08T07:15:00.000Z",
  },
  {
    id: "rpt-finance-march",
    title: "Laporan Keuangan Maret 2026",
    description: "Rekap cashflow dan operasional bulanan.",
    category: "Finance",
    fileType: "EXCEL",
    status: "PUBLISHED",
    tags: ["finance", "monthly"],
    printCount: 33,
    createdBy: { id: "usr-siti", name: "Siti Rahayu", department: "Finance" },
    createdAt: "2026-03-02T02:10:00.000Z",
    updatedAt: "2026-03-08T06:45:00.000Z",
  },
  {
    id: "rpt-ops-maintenance",
    title: "Checklist Maintenance Printer",
    description: "Laporan pemeliharaan printer per lantai.",
    category: "Operations",
    fileType: "PDF",
    status: "DRAFT",
    tags: ["maintenance", "printer"],
    printCount: 9,
    createdBy: { id: "usr-eko", name: "Eko Prasetyo", department: "Operations" },
    createdAt: "2026-03-04T10:20:00.000Z",
    updatedAt: "2026-03-07T16:20:00.000Z",
  },
];

export const demoPrints: PrintHistoryItem[] = [
  {
    id: "pl-1",
    printedAt: "2026-03-08T09:15:00.000Z",
    copies: 2,
    pageCount: 12,
    printerName: "HP-Floor2",
    status: "SUCCESS",
    duration: 4320,
    report: { id: "rpt-sales-q1", title: "Rekap Penjualan Q1 2026", category: "Sales" },
    user: { id: "usr-siti", name: "Siti Rahayu", department: "Sales" },
  },
  {
    id: "pl-2",
    printedAt: "2026-03-08T09:42:00.000Z",
    copies: 1,
    pageCount: 7,
    printerName: "HP-Floor3",
    status: "FAILED",
    duration: 2100,
    report: { id: "rpt-finance-march", title: "Laporan Keuangan Maret 2026", category: "Finance" },
    user: { id: "usr-budi", name: "Budi Santoso", department: "Finance" },
  },
  {
    id: "pl-3",
    printedAt: "2026-03-08T10:05:00.000Z",
    copies: 3,
    pageCount: 9,
    printerName: "Canon-RoomA",
    status: "SUCCESS",
    duration: 3980,
    report: { id: "rpt-sales-q1", title: "Rekap Penjualan Q1 2026", category: "Sales" },
    user: { id: "usr-eko", name: "Eko Prasetyo", department: "Operations" },
  },
];

export const demoFeed: PrintFeedItem[] = demoPrints.map((item) => ({
  ...item,
  report: item.report,
  user: item.user,
}));

export const demoDashboardStats: DashboardStats = {
  summary: {
    totalReports: 1284,
    todayPrints: 47,
    totalPages: 12930,
    activeUsers: 23,
    todayPrintChange: 8.4,
    reportsChange: 12.1,
    pagesChange: 5.2,
    activeUsersChangeLabel: "3 user baru hari ini",
    failedPrints: 3,
  },
  hourlyTrend: [
    { label: "08:00", count: 12 },
    { label: "09:00", count: 18 },
    { label: "10:00", count: 22 },
    { label: "11:00", count: 19 },
    { label: "12:00", count: 11 },
    { label: "13:00", count: 14 },
    { label: "14:00", count: 17 },
    { label: "15:00", count: 9 },
  ],
  topReports: [
    { reportId: "rpt-sales-q1", title: "Rekap Penjualan Q1 2026", printCount: 47 },
    { reportId: "rpt-finance-march", title: "Laporan Keuangan Maret 2026", printCount: 33 },
    { reportId: "rpt-ops-maintenance", title: "Checklist Maintenance Printer", printCount: 9 },
  ],
  byDepartment: [
    { name: "Finance", value: 38 },
    { name: "Sales", value: 29 },
    { name: "Operations", value: 18 },
    { name: "HR", value: 15 },
  ],
  heatmap: [
    { day: "Sen", hour: 9, value: 14 },
    { day: "Sen", hour: 10, value: 21 },
    { day: "Sel", hour: 9, value: 12 },
    { day: "Rab", hour: 11, value: 17 },
    { day: "Kam", hour: 14, value: 9 },
    { day: "Jum", hour: 10, value: 15 },
  ],
  recentPrints: demoPrints,
};
